example_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('rhizom.urls', namespace='rhizom')),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('allauth.urls')),
    url(r'^pages/?', include('django.contrib.flatpages.urls')),
]

rhizom/urls.py
from django.conf.urls import include, url

from .views import index, profile, graph, admin, edit

app_name = "rhizom"

graph_patterns = [
    url(r'^$', graph.GraphView.as_view(), name='graph_view'),
    url(r'^data.js$', graph.GraphData.as_view(), name='graph_data'),
    url(r'^export/(?P<name>.+)\.(?P<format>[a-z]+)$',
        graph.GraphExport.as_view(), name='graph_export'),
    url(r'^edit/$', edit.GraphEditAll.as_view(), name='graph_edit'),
    url(r'^edit/person/(?P<person>\d+)$', edit.GraphEditPerson.as_view(),
        name='graph_edit_person'),
    url(r'^edit/relationships/$', edit.GraphRelAdd.as_view(),
        name='graph_edit_relationship_add'),
    url(r'^edit/relationships/(?P<rel>\d+)$', edit.GraphRelEdit.as_view(),
        name='graph_edit_relationship_edit'),
    url(r'^admin/$', admin.GraphAdmin.as_view(), name='graph_admin'),
    url(r'^admin/reltype/$', admin.GraphRelType.as_view(),
        name='graph_admin_reltypes'),
    url(r'^admin/reltype/(?P<pk>\d+)$', admin.GraphRelType.as_view(),
        name='graph_admin_reltypes'),
    url(r'^admin/access/$', admin.GraphAccess.as_view(),
        name='graph_admin_access'),
    url(r'^admin/access/(?P<pk>\d+)$', admin.GraphAccess.as_view(),
        name='graph_admin_access'),
    url(r'^admin/find-username$', admin.FindUsername.as_view(),
        name='graph_admin_find_username'),
]

urlpatterns = [
    url(r'^$', index.IndexView.as_view(), name="index"),
    url(r'^profile/$', profile.ProfileView.as_view(), name="profile"),
    url(r'^graph/(?P<graph>\d+)/', include(graph_patterns)),
    url(r'^pages/?', include('django.contrib.flatpages.urls')),
]

rhizom/views/admin.py
import json

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import (
    HttpResponse, HttpResponseRedirect, QueryDict, JsonResponse)
from django.shortcuts import get_object_or_404, redirect
from django.template import loader
from django.urls import reverse
from django.utils.translation import ugettext as _
from django.views.generic import View
from django.views.generic.edit import UpdateView

from rhizom.forms import GraphProperties, NewAccess, RelationshipTypes
from rhizom.models.graph import Graph
from rhizom.models.permission import Permission, get_perm_choices
from rhizom.models.person import Person
from rhizom.models.relationship import RelationshipType


class GraphAdmin(UpdateView):

    template_name = "rhizom/graph_admin.html"
    model = Graph
    pk_url_kwarg = "graph"
    context_object_name = "graph"
    form_class = GraphProperties

    def get_object(self):
        obj = super().get_object()
        if not obj.allowed_for(self.request.user, "admin"):
            raise PermissionDenied
        return obj

    def get_success_url(self):
        return reverse("rhizom:graph_admin", kwargs={"graph": self.object.pk})

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update(dict(instance=self.object, prefix="graphprops"))
        return kwargs

    def get_form(self):
        form = super().get_form()
        form.fields["center"].queryset = Person.objects.filter(
            graph=self.object)
        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        messages.success(self.request, _("Graph updated."))
        return super().form_valid(form)

    def post(self, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        # Graph: properties edition
        if self.request.POST.get("formname") == "graphprops":
            if form.is_valid():
                return self.form_valid(form)
            else:
                return self.form_invalid(form)
        # Graph: import
        if self.request.POST.get("formname") == "graphimport":
            if "import" not in self.request.FILES:
                messages.error(self.request, _("No graph data."))
                return HttpResponseRedirect(self.get_success_url())
            try:
                data = json.loads(
                    self.request.FILES["import"].read().decode("utf-8"))
            except ValueError as e:
                messages.error(
                    self.request,
                    _("Invalid graph data: %(error)s", {"error": str(e)}))
                return HttpResponseRedirect(self.get_success_url())
            self.object.import_dict(data)
            self.object.save()
            messages.success(self.request, _("Graph imported."))
            return HttpResponseRedirect(self.get_success_url())
        # Graph: deletion
        if self.request.POST.get("formname") == "graphdel":
            self.object.delete()
            messages.success(self.request, _("Graph deleted."))
            return redirect("rhizom:index")
        return self.render_to_response(self.get_context_data(form=form))


class GraphDynamicTable(View):

    template_name = None
    model = None
    form_class = None
    messages = {
        "added": None,
        "updated": None,
        "deleted": None,
    }
    replace_on_delete = False

    def _get_graph(self):
        graph = get_object_or_404(Graph, pk=int(self.kwargs["graph"]))
        if not graph.allowed_for(self.request.user, "admin"):
            raise PermissionDenied
        return graph

    def _get_instance(self):
        return get_object_or_404(
            self.model,
            graph=self.graph,
            pk=int(self.kwargs["pk"])
            )

    def get_context_data(self, form):
        return dict(graph=self.graph, form=form)

    def _get_content(self, form):
        return loader.render_to_string(
            self.template_name, self.get_context_data(form), self.request)

    def form_invalid(self, form):
        return JsonResponse(
            {"status": "error", "action": "replace-table",
             "content": self._get_content(form)})

    def get(self, *args, **kwargs):
        self.graph = self._get_graph()
        form = self.form_class(graph=self.graph)
        return HttpResponse(self._get_content(form))

    def post(self, *args, **kwargs):
        self.graph = self._get_graph()
        form = self.form_class(self.request.POST, graph=self.graph)
        if not form.is_valid():
            return self.form_invalid(form)
        form.save()
        form = self.form_class(graph=self.graph)  # get a blank form
        return JsonResponse(
            {"status": "OK", "action": "replace-table",
             "content": self._get_content(form),
             "message": self.messages["added"]})

    def put(self, *args, **kwargs):
        self.graph = self._get_graph()
        instance = self._get_instance()
        put_data = QueryDict(self.request.body, encoding=self.request.encoding)
        form = self.form_class(
            put_data, graph=self.graph, instance=instance)
        if not form.is_valid():
            return self.form_invalid(form)
        form.save()
        form = self.form_class(graph=self.graph)  # get a blank form
        return JsonResponse(
            {"status": "OK", "action": "replace-table",
             "content": self._get_content(form),
             "message": self.messages["updated"]})

    def delete(self, *args, **kwargs):
        self.graph = self._get_graph()
        instance = self._get_instance()
        instance.delete()
        response = {"status": "OK", "message": self.messages["deleted"]}
        if self.replace_on_delete:
            response["action"] = "replace-table"
            form = self.form_class(graph=self.graph)  # get a blank form
            response["content"] = self._get_content(form)
        else:
            response["action"] = "delete"
        return JsonResponse(response)


class GraphRelType(GraphDynamicTable):

    template_name = "rhizom/graph_admin/edit_reltypes.html"
    model = RelationshipType
    form_class = RelationshipTypes
    messages = {
        "added": _("Relationship type added."),
        "updated": _("Relationship type modified."),
        "deleted": _("Relationship type removed."),
    }


class GraphAccess(GraphDynamicTable):

    template_name = "rhizom/graph_admin/edit_accesses.html"
    model = Permission
    form_class = NewAccess
    messages = {
        "added": _("Access added."),
        "updated": _("Access modified."),
        "deleted": _("Access removed."),
    }
    replace_on_delete = True

    def get_context_data(self, form):
        context = super().get_context_data(form)
        context["perm_choices"] = get_perm_choices()
        context["has_public_access"] = Permission.objects.filter(
            graph=self.graph, user=None).exists()
        return context


class FindUsername(LoginRequiredMixin, View):

    def get(self, *args, **kwargs):
        User = get_user_model()
        query = self.request.GET.get("q")
        if not query:
            usernames = []
        else:
            usernames = User.objects.filter(
                username__icontains=query
                ).values_list("username", flat=True)
        return JsonResponse(list(usernames), safe=False)

rhizom/views/edit.py
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.http import JsonResponse, QueryDict
from django.shortcuts import get_object_or_404
from django.template import loader
from django.utils.timezone import now
from django.utils.translation import ugettext as _
from django.views.generic import TemplateView, View
from django.views.generic.detail import DetailView

from rhizom.models.graph import Graph
from rhizom.models.person import Person
from rhizom.models.relationship import Relationship
from rhizom.forms import NewRelationship, RelationshipForm


class GraphEditAll(DetailView):

    template_name = "rhizom/graph_edit.html"
    model = Graph
    pk_url_kwarg = "graph"
    context_object_name = "graph"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        newrel_form = NewRelationship(graph=self.object)
        context.update(dict(newrel_form=newrel_form))
        return context

    def get(self, *args, **kwargs):
        self.object = self.get_object()
        if not self.object.allowed_for(self.request.user, "edit"):
            raise PermissionDenied
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)


class GraphEditPerson(TemplateView):

    template_name = "rhizom/graph_edit.html"
    model = Graph
    context_object_name = "graph"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        graph = get_object_or_404(Graph, pk=int(self.kwargs["graph"]))
        if not graph.allowed_for(self.request.user, "edit"):
            raise PermissionDenied
        person = get_object_or_404(
            Person, pk=self.kwargs["person"], graph=graph)
        newrel_form = NewRelationship(graph=graph, person=person)
        relationships = []
        for rel in person.rels_as_source.all():
            rel.other = rel.target
            relationships.append(rel)
        for rel in person.rels_as_target.all():
            rel.other = rel.source
            relationships.append(rel)
        relationships.sort(key=lambda rel: rel.other.name)
        context.update(dict(
            graph=graph,
            newrel_form=newrel_form,
            person=person,
            relationships=relationships,
        ))
        return context


class GraphRelAdd(View):

    template_name = "rhizom/graph_edit/add_rel.html"

    def post(self, *args, **kwargs):
        graph = get_object_or_404(Graph, pk=int(self.kwargs["graph"]))
        if not graph.allowed_for(self.request.user, "edit"):
            raise PermissionDenied
        try:
            person = int(self.request.POST["person"])
        except (KeyError, ValueError):
            person = None
        else:
            person = get_object_or_404(Person, pk=person)
        newrel_form = NewRelationship(
            self.request.POST, graph=graph, person=person)
        if not newrel_form.is_valid():
            content = loader.render_to_string(
                "rhizom/graph_edit/add_rel.html",
                {"graph": graph, "newrel_form": newrel_form, "person": person},
                self.request)
            return JsonResponse(
                {"status": "error", "action": "replace", "content": content})
        source, _created = Person.objects.get_or_create(
            graph=graph, name=newrel_form.cleaned_data["source"])
        target, _created = Person.objects.get_or_create(
            graph=graph, name=newrel_form.cleaned_data["target"])
        if source.pk > target.pk:
            source, target = target, source  # source is always the lowest id
        if Relationship.objects.filter(
                source=source, target=target,
                reltype__pk=newrel_form.cleaned_data["rtype"]).exists():
            content = loader.render_to_string(
                "rhizom/graph_edit/add_rel.html",
                {"graph": graph, "newrel_form": newrel_form, "person": person},
                self.request)
            return JsonResponse(
                {"status": "error", "action": "replace", "content": content,
                 "message": _("This relationship already exists.")})
        newlink = Relationship.objects.create(
            source=source, target=target,
            reltype_id=newrel_form.cleaned_data["rtype"],
            dotted=newrel_form.cleaned_data["dotted"])
        graph.last_modification = now()
        graph.save()
        result = {"status": "OK", "message": _("Relationship added.")}
        if person:
            if source.pk == person.pk:
                newlink.other = newlink.target
            elif target.pk == person.pk:
                newlink.other = newlink.source
            content = loader.render_to_string(
                "rhizom/graph_edit/edit_rel.html",
                {"graph": graph, "rel": newlink}, self.request)
            result.update({"action": "add", "content": content})
        else:
            newrel_form = NewRelationship(graph=graph)  # Get a clean instance
            content = loader.render_to_string(
                "rhizom/graph_edit/new_rel.html",
                {"graph": graph, "newrel_form": newrel_form},
                self.request)
            result.update({"action": "replace", "content": content})
        return JsonResponse(result)


class GraphRelEdit(View):

    def _get_rel(self):
        self.graph = get_object_or_404(Graph, pk=int(self.kwargs["graph"]))
        if not self.graph.allowed_for(self.request.user, "edit"):
            raise PermissionDenied
        return get_object_or_404(Relationship, pk=int(self.kwargs["rel"]))

    def put(self, *args, **kwargs):
        rel = self._get_rel()
        put_data = QueryDict(self.request.body, encoding=self.request.encoding)
        form = RelationshipForm(put_data, instance=rel)
        if not form.is_valid():
            messages = []
            for fieldname, errors in form.errors.items():
                for error in errors:
                    messages.append("{}: {}".format(
                        form.fields[fieldname].label, error))
            return JsonResponse({
                "status": "error",
                "message": "<br/>".join(messages),
                })
        if not form.has_changed():
            return JsonResponse({
                "status": "OK",
                "message": _("No modification."),
                })
        form.save()
        self.graph.last_modification = now()
        self.graph.save()
        rel.other = Person.objects.get(pk=int(put_data["other"]))
        assert rel.other.pk in (rel.source.pk, rel.target.pk)
        content = loader.render_to_string(
            "rhizom/graph_edit/edit_rel.html",
            dict(graph=self.graph, rel=rel), self.request)
        return JsonResponse(dict(
                status="OK", action="replace", content=content,
                message=_("Relationship modified.")))

    def delete(self, *args, **kwargs):
        rel = self._get_rel()
        persons = (rel.source, rel.target)
        rel.delete()
        # Cleanup orphans
        for person in persons:
            if not Relationship.objects.filter(
                    Q(source=person) | Q(target=person)
                    ).exists():
                person.delete()
        self.graph.last_modification = now()
        self.graph.save()
        return JsonResponse(dict(
                status="OK", action="delete",
                message=_("Relationship removed.")))

rhizom/views/profile.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic.edit import UpdateView

from rhizom.forms import UserProfileForm


class ProfileView(LoginRequiredMixin, UpdateView):

    template_name = "rhizom/profile/profile.html"
    model = get_user_model()
    form_class = UserProfileForm
    success_url = reverse_lazy("rhizom:profile")

    def get_object(self):
        return self.request.user

    def get_initial(self):
        initial = super().get_initial()
        initial["locale"] = (
            self.object.rhizom_profile.locale or self.request.LANGUAGE_CODE)
        return initial

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        return kwargs

rhizom/templates/rhizom/graph_admin.html
{% extends "rhizom/base.html" %}
{% load i18n %}
{% load static %}
{% load bootstrap_tags %}

{% block head_title %}{% trans "Administration" %} | {{ block.super }}{% endblock %}

{% block content %}

<h3>{% trans "Graph properties" %}</h3>

<form role="form" method="post" class="form-horizontal">
    <input type="hidden" name="formname" value="graphprops" />
    {% bootstrap_form_horizontal form 2 4 _("Change") %}
</form>

<hr />

<h3>{% trans "Relationship types" %}</h3>

<div class="loadable" data-load-from="{% url 'rhizom:graph_admin_reltypes' graph=graph.pk %}"></div>

<hr />

<h3>{% trans "Authorizations" %}</h3>

<div class="loadable" data-load-from="{% url 'rhizom:graph_admin_access' graph=graph.pk %}"></div>

<hr />

<h3>{% trans "Import / Export" %}</h3>

<div class="col-md-6 text-center">
    <a class="btn btn-primary"
       href="{% url "rhizom:graph_export" graph=graph.pk name=graph.name format="json" %}">
       {% trans "Export graph" %}
    </a>
</div>
<form role="form" method="post" enctype="multipart/form-data"
      class="form-inline col-md-6 text-center with-loading-button"
      action="{% url "rhizom:graph_admin" graph=graph.pk %}">
    {% csrf_token %}
    <input type="hidden" name="formname" value="graphimport" />
    <input type="file" class="form-control" name="import"/>
    <button type="submit" class="btn btn-primary"
        data-loading-text="{% trans 'Importing...' %}">{% trans "Import graph" %}</button>
</form>
<div class="clearfix"></div>

<hr />

<h3>{% trans "Deletion" %}</h3>

<p>
    <form role="form" method="post" class="form-delete"
          action="{% url "rhizom:graph_admin" graph=graph.pk %}">
    {% csrf_token %}
    <input type="hidden" name="formname" value="graphdel" />
    <button type="submit" class="btn btn-danger"
        data-confirm="{% trans "Undoing this is impossible. Go on?" %}"
        >{% blocktrans with name=graph.name %}Delete {{ name }}{% endblocktrans %}</button>
    </form>
</p>

{% endblock %}


{% block extra_head %}
{{ block.super }}
<link rel="stylesheet" href="{% static "rhizom/lib/spectrum/spectrum.css" %}" />
{% endblock %}
{% block more_js %}
{{ block.super }}
<script src="{% static "rhizom/lib/spectrum/spectrum.js" %}"></script>
<script>
    $(function() {
        $("form.form-delete button").click(function(e) {
            var response = confirm($(this).attr("data-confirm"));
            if (!response) {
                e.preventDefault();
            }
        });
    });
</script>
{% endblock %}

rhizom/templates/rhizom/graph_edit.html
{% load i18n %}
{% load rhizom %}

{% if graph.relationshiptype_set.count > 0 %} {# There is at least a relationship type defined #}

{% if person %}
<h4>
{% blocktrans with name=person.name %}
Relationships for <strong>{{ name }}</strong>
{% endblocktrans %}
</h4>

<div class="form-table">
    <div class="form-table-head">
        <div class="form-table-cell">{% trans "With" %}</div>
        <div class="form-table-cell">{% trans "Type" %}</div>
        <div class="form-table-cell">{% trans "Dotted" %}</div>
        <div class="form-table-cell"></div>
    </div>
    {% include "rhizom/graph_edit/add_rel.html" %}
    {% for rel in relationships %}
        {% include "rhizom/graph_edit/edit_rel.html" %}
    {% endfor %}
</div>

{% else %}

<h4>{% trans "New relationship" %}</h4>

{% include "rhizom/graph_edit/new_rel.html" %}

{% endif %}


{% else %} {# There is no relationship type defined #}
<div class="alert alert-danger">
    {% trans "No relationship type has been configured yet." %}
    {% if user|has_graph_admin_perm:graph %}
        {% url "rhizom:graph_admin" graph=graph.id as admin_url %}
        {% blocktrans %}
        Start by adding one <a href="{{ admin_url }}">on the admin page</a>.
        {% endblocktrans %}
    {% else %}
        {% trans "Ask the graph admin to add some." %}
    {% endif %}
</div>
{% endif %}

rhizom/templates/rhizom/graph_view.html
{% extends "rhizom/base.html" %}
{% load i18n %}
{% load static %}
{% load rhizom %}

{% block extra_head %}
{{ block.super }}
<style>
    {% for rtype in graph.relationshiptype_set.all %}
    path.link.{{ rtype.cssname }} {
        stroke: {{ rtype.color }};
    }
    #legend .{{ rtype.cssname }} {
        background-color: {{ rtype.color }};
    }
    {% endfor %}
</style>
{% endblock %}


{% block content %}

<div id="graph-container">

{# Edit panel #}
<div class="edit-panel">
    <div class="edit-panel-content">
        <div class="ajaxloader">
            <img src="{% static "rhizom/img/ajax-loader-big.gif" %}"
                 alt="{% trans "Loading..." %}" />
        </div>
        <div class="edit-panel-toolbar">
            <a data-container="body" data-toggle="popover" data-placement="bottom" data-trigger="hover"
               href="" title="{% trans "Help" %}"
               data-content="{% trans "Click on a person to edit their relationships, click on the graph background to add new persons." %}">
                <span class="glyphicon glyphicon-question-sign"></span>
            </a>
            <a href="" title="{% trans "Close edit panel" %}" class="edit-panel-close">
                <span class="glyphicon glyphicon-remove-circle"></span>
            </a>
        </div>
        <div class="edit-panel-form"
             data-base-url="{% url "rhizom:graph_edit" graph=graph.id %}">
        </div>
    </div>
</div>


{# Graph #}
<div id="graph">
    <div class="ajaxloader">
        <img src="{% static "rhizom/img/ajax-loader-big.gif" %}"
             alt="Loading..." />
    </div>
</div>

</div>


<div id="graph-footer" class="row">
<div id="legend" class="row">
    <strong>{% trans "Legend:" %}</strong>
    <ul>
        {% for rtype in graph.relationshiptype_set.all %}
        <li><a href="" data-rtype="{{ rtype.cssname }}"
               data-toggle="tooltip" data-placement="top"
               title="{% trans "Hide or show this type" %}">
            <span class="{{ rtype.cssname }}"> </span> {{ rtype.name }}
        </a></li>
        {% endfor %}
    </ul>
</div>
<p>
    <span class="glyphicon glyphicon-user"></span>
    {% blocktrans with pnum=graph.person_set.count rnum=graph.relationships|length %}
    {{ pnum }} persons, {{ rnum }} relationships.
    {% endblocktrans %}
</p>
<p>
    {% trans "Drag to move, mouse wheel to zoom/unzoom, double click to recenter the view." %}
</p>
<ul id="graph-actions" class="list-inline">
    <li><strong>{% trans "Actions :" %}</strong></li>
    {% if user|has_graph_edit_perm:graph %}
    <li data-toggle="buttons">
        <label class="btn btn-sm btn-info" id="btn-edit-mode">
            <input type="checkbox" autocomplete="off" />
            <span class="glyphicon glyphicon-edit"></span>
            {% trans "Edit mode" %}
        </label>
    </li>
    {% endif %}
    <li><button class="btn btn-sm btn-default" id="btn-stop">
        <span class="glyphicon glyphicon-pause"></span>
        {% trans "Freeze" %}</button>
    </li>
    <li data-toggle="buttons">
        <label class="btn btn-sm btn-default" id="btn-anonymous">
            <input type="checkbox" autocomplete="off" />
            <span class="glyphicon glyphicon-eye-close"></span>
            <span class="glyphicon glyphicon-eye-open"></span>
            {% trans "Anonymous" %}
        </label>
    </li>
    <!-- <button onclick="graph.redraw();">{% trans "Redraw" %}</button> -->
    <li>
        <form action="{% url "rhizom:graph_export" graph=graph.id name=graph.name format="svg" %}"
              method="post" id="export-svg" target="_blank" style="display:inline">
            {% csrf_token %}
            <input type="hidden" name="svg"/>
            <button type="submit" class="btn btn-sm btn-default" title="{% trans "Export to SVG" %}">
                <span class="glyphicon glyphicon-share"></span> SVG
            </button>
        </form>
    </li>
    <li><label for="linkdistance">{% trans "Link length:" %}</label>
        <span id="linkdistance"></span>
    </li>
</ul>
</div> <!-- /graph-footer -->



{% endblock %}

{% block more_js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js"></script>
<script src="{% static "rhizom/js/graph.js" %}"></script>
<script>
//<![CDATA[
    graph = setup_graph_page("{% url "rhizom:graph_data" graph=graph.id %}");
    setup_editor_page(graph);
//]]>
</script>
{% endblock %}

rhizom/templates/rhizom/index.html
{% extends "rhizom/base.html" %}
{% load i18n %}
{% load static %}
{% load bootstrap_tags %}

{% block content %}

<div class="jumbotron">
    <h1>Rhizom <img src="{% static "rhizom/img/logo-64.png" %}" alt="logo" /></h1>
    <p>
        {% trans "Visualize your relationship network." %}
        <a href="https://gitlab.com/abompard/rhizom" class="btn btn-primary">
            {% trans "Learn more" %}
        </a>
    </p>
</div>

{% if paginator.count %}

<h2>{% trans "Available graphs:" %}</h2>

<ul class="lead graphlist">
    {% for graph in graphs %}
    <li>
        <a href="{% url 'rhizom:graph_view' graph=graph.pk %}">{{ graph.name }}</a>
        <span class="text-muted smaller">
            (<span class="glyphicon glyphicon-user"></span>
            {{ graph.person_set.count }} / {{ graph.relationships.count }})
        </span>
    </li>
    {% endfor %}
</ul>

{% if is_paginated and paginator.num_pages > 1 %}
    {% include "bootstrap/pagination.html" %}
{% endif %}

{% else %}

<p>{% trans "No graph available." %}</p>

{% endif %}

{% if user.is_authenticated %}

<div class="newgraph">
<hr />

<h3>{% trans "New graph" %}</h3>

<form role="form" method="post" class="form-inline">
    {% bootstrap_form_inline new_form %}
    <button class="btn btn-primary" type="submit"
            name="formname" value="new">
        {% trans "Create" %}
    </button>
</form>

{% if graphs %}
<hr />
<form role="form" method="post" class="form-inline">
    {% bootstrap_form_inline copy_form %}
    <button class="btn btn-primary" type="submit"
            name="formname" value="copy">
        {% trans "Copy" %}
    </button>
</form>
{% endif %}

</div>

{% else %}

<p class="alert alert-info">
{% url "account_login" as login_url %}
{% blocktrans %}
You need to <a href="{{ login_url }}">login</a> to see your graphs or create new graphs.
{% endblocktrans %}
</p>

{% endif %}

{% endblock %}