example_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('rhizom.urls', namespace='rhizom')),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('allauth.urls')),
    url(r'^pages/?', include('django.contrib.flatpages.urls')),
]

rhizom/urls.py
from django.conf.urls import include, url

from .views import index, profile, graph, admin, edit

app_name = "rhizom"

graph_patterns = [
    url(r'^$', graph.GraphView.as_view(), name='graph_view'),
    url(r'^data.js$', graph.GraphData.as_view(), name='graph_data'),
    url(r'^export/(?P<name>.+)\.(?P<format>[a-z]+)$',
        graph.GraphExport.as_view(), name='graph_export'),
    url(r'^edit/$', edit.GraphEditAll.as_view(), name='graph_edit'),
    url(r'^edit/person/(?P<person>\d+)$', edit.GraphEditPerson.as_view(),
        name='graph_edit_person'),
    url(r'^edit/relationships/$', edit.GraphRelAdd.as_view(),
        name='graph_edit_relationship_add'),
    url(r'^edit/relationships/(?P<rel>\d+)$', edit.GraphRelEdit.as_view(),
        name='graph_edit_relationship_edit'),
    url(r'^admin/$', admin.GraphAdmin.as_view(), name='graph_admin'),
    url(r'^admin/reltype/$', admin.GraphRelType.as_view(),
        name='graph_admin_reltypes'),
    url(r'^admin/reltype/(?P<pk>\d+)$', admin.GraphRelType.as_view(),
        name='graph_admin_reltypes'),
    url(r'^admin/access/$', admin.GraphAccess.as_view(),
        name='graph_admin_access'),
    url(r'^admin/access/(?P<pk>\d+)$', admin.GraphAccess.as_view(),
        name='graph_admin_access'),
    url(r'^admin/find-username$', admin.FindUsername.as_view(),
        name='graph_admin_find_username'),
]

urlpatterns = [
    url(r'^$', index.IndexView.as_view(), name="index"),
    url(r'^profile/$', profile.ProfileView.as_view(), name="profile"),
    url(r'^graph/(?P<graph>\d+)/', include(graph_patterns)),
    url(r'^pages/?', include('django.contrib.flatpages.urls')),
]

rhizom/views/admin.py
import json

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import (
    HttpResponse, HttpResponseRedirect, QueryDict, JsonResponse)
from django.shortcuts import get_object_or_404, redirect
from django.template import loader
from django.urls import reverse
from django.utils.translation import ugettext as _
from django.views.generic import View
from django.views.generic.edit import UpdateView

from rhizom.forms import GraphProperties, NewAccess, RelationshipTypes
from rhizom.models.graph import Graph
from rhizom.models.permission import Permission, get_perm_choices
from rhizom.models.person import Person
from rhizom.models.relationship import RelationshipType


class GraphAdmin(UpdateView):

    template_name = "rhizom/graph_admin.html"
    model = Graph
    pk_url_kwarg = "graph"
    context_object_name = "graph"
    form_class = GraphProperties

    def get_object(self):
        obj = super().get_object()
        if not obj.allowed_for(self.request.user, "admin"):
            raise PermissionDenied
        return obj

    def get_success_url(self):
        return reverse("rhizom:graph_admin", kwargs={"graph": self.object.pk})

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update(dict(instance=self.object, prefix="graphprops"))
        return kwargs

    def get_form(self):
        form = super().get_form()
        form.fields["center"].queryset = Person.objects.filter(
            graph=self.object)
        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        messages.success(self.request, _("Graph updated."))
        return super().form_valid(form)

    def post(self, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        # Graph: properties edition
        if self.request.POST.get("formname") == "graphprops":
            if form.is_valid():
                return self.form_valid(form)
            else:
                return self.form_invalid(form)
        # Graph: import
        if self.request.POST.get("formname") == "graphimport":
            if "import" not in self.request.FILES:
                messages.error(self.request, _("No graph data."))
                return HttpResponseRedirect(self.get_success_url())
            try:
                data = json.loads(
                    self.request.FILES["import"].read().decode("utf-8"))
            except ValueError as e:
                messages.error(
                    self.request,
                    _("Invalid graph data: %(error)s", {"error": str(e)}))
                return HttpResponseRedirect(self.get_success_url())
            self.object.import_dict(data)
            self.object.save()
            messages.success(self.request, _("Graph imported."))
            return HttpResponseRedirect(self.get_success_url())
        # Graph: deletion
        if self.request.POST.get("formname") == "graphdel":
            self.object.delete()
            messages.success(self.request, _("Graph deleted."))
            return redirect("rhizom:index")
        return self.render_to_response(self.get_context_data(form=form))


class GraphDynamicTable(View):

    template_name = None
    model = None
    form_class = None
    messages = {
        "added": None,
        "updated": None,
        "deleted": None,
    }
    replace_on_delete = False

    def _get_graph(self):
        graph = get_object_or_404(Graph, pk=int(self.kwargs["graph"]))
        if not graph.allowed_for(self.request.user, "admin"):
            raise PermissionDenied
        return graph

    def _get_instance(self):
        return get_object_or_404(
            self.model,
            graph=self.graph,
            pk=int(self.kwargs["pk"])
            )

    def get_context_data(self, form):
        return dict(graph=self.graph, form=form)

    def _get_content(self, form):
        return loader.render_to_string(
            self.template_name, self.get_context_data(form), self.request)

    def form_invalid(self, form):
        return JsonResponse(
            {"status": "error", "action": "replace-table",
             "content": self._get_content(form)})

    def get(self, *args, **kwargs):
        self.graph = self._get_graph()
        form = self.form_class(graph=self.graph)
        return HttpResponse(self._get_content(form))

    def post(self, *args, **kwargs):
        self.graph = self._get_graph()
        form = self.form_class(self.request.POST, graph=self.graph)
        if not form.is_valid():
            return self.form_invalid(form)
        form.save()
        form = self.form_class(graph=self.graph)  # get a blank form
        return JsonResponse(
            {"status": "OK", "action": "replace-table",
             "content": self._get_content(form),
             "message": self.messages["added"]})

    def put(self, *args, **kwargs):
        self.graph = self._get_graph()
        instance = self._get_instance()
        put_data = QueryDict(self.request.body, encoding=self.request.encoding)
        form = self.form_class(
            put_data, graph=self.graph, instance=instance)
        if not form.is_valid():
            return self.form_invalid(form)
        form.save()
        form = self.form_class(graph=self.graph)  # get a blank form
        return JsonResponse(
            {"status": "OK", "action": "replace-table",
             "content": self._get_content(form),
             "message": self.messages["updated"]})

    def delete(self, *args, **kwargs):
        self.graph = self._get_graph()
        instance = self._get_instance()
        instance.delete()
        response = {"status": "OK", "message": self.messages["deleted"]}
        if self.replace_on_delete:
            response["action"] = "replace-table"
            form = self.form_class(graph=self.graph)  # get a blank form
            response["content"] = self._get_content(form)
        else:
            response["action"] = "delete"
        return JsonResponse(response)


class GraphRelType(GraphDynamicTable):

    template_name = "rhizom/graph_admin/edit_reltypes.html"
    model = RelationshipType
    form_class = RelationshipTypes
    messages = {
        "added": _("Relationship type added."),
        "updated": _("Relationship type modified."),
        "deleted": _("Relationship type removed."),
    }


class GraphAccess(GraphDynamicTable):

    template_name = "rhizom/graph_admin/edit_accesses.html"
    model = Permission
    form_class = NewAccess
    messages = {
        "added": _("Access added."),
        "updated": _("Access modified."),
        "deleted": _("Access removed."),
    }
    replace_on_delete = True

    def get_context_data(self, form):
        context = super().get_context_data(form)
        context["perm_choices"] = get_perm_choices()
        context["has_public_access"] = Permission.objects.filter(
            graph=self.graph, user=None).exists()
        return context


class FindUsername(LoginRequiredMixin, View):

    def get(self, *args, **kwargs):
        User = get_user_model()
        query = self.request.GET.get("q")
        if not query:
            usernames = []
        else:
            usernames = User.objects.filter(
                username__icontains=query
                ).values_list("username", flat=True)
        return JsonResponse(list(usernames), safe=False)

rhizom/views/edit.py
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.http import JsonResponse, QueryDict
from django.shortcuts import get_object_or_404
from django.template import loader
from django.utils.timezone import now
from django.utils.translation import ugettext as _
from django.views.generic import TemplateView, View
from django.views.generic.detail import DetailView

from rhizom.models.graph import Graph
from rhizom.models.person import Person
from rhizom.models.relationship import Relationship
from rhizom.forms import NewRelationship, RelationshipForm


class GraphEditAll(DetailView):

    template_name = "rhizom/graph_edit.html"
    model = Graph
    pk_url_kwarg = "graph"
    context_object_name = "graph"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        newrel_form = NewRelationship(graph=self.object)
        context.update(dict(newrel_form=newrel_form))
        return context

    def get(self, *args, **kwargs):
        self.object = self.get_object()
        if not self.object.allowed_for(self.request.user, "edit"):
            raise PermissionDenied
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)


class GraphEditPerson(TemplateView):

    template_name = "rhizom/graph_edit.html"
    model = Graph
    context_object_name = "graph"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        graph = get_object_or_404(Graph, pk=int(self.kwargs["graph"]))
        if not graph.allowed_for(self.request.user, "edit"):
            raise PermissionDenied
        person = get_object_or_404(
            Person, pk=self.kwargs["person"], graph=graph)
        newrel_form = NewRelationship(graph=graph, person=person)
        relationships = []
        for rel in person.rels_as_source.all():
            rel.other = rel.target
            relationships.append(rel)
        for rel in person.rels_as_target.all():
            rel.other = rel.source
            relationships.append(rel)
        relationships.sort(key=lambda rel: rel.other.name)
        context.update(dict(
            graph=graph,
            newrel_form=newrel_form,
            person=person,
            relationships=relationships,
        ))
        return context


class GraphRelAdd(View):

    template_name = "rhizom/graph_edit/add_rel.html"

    def post(self, *args, **kwargs):
        graph = get_object_or_404(Graph, pk=int(self.kwargs["graph"]))
        if not graph.allowed_for(self.request.user, "edit"):
            raise PermissionDenied
        try:
            person = int(self.request.POST["person"])
        except (KeyError, ValueError):
            person = None
        else:
            person = get_object_or_404(Person, pk=person)
        newrel_form = NewRelationship(
            self.request.POST, graph=graph, person=person)
        if not newrel_form.is_valid():
            content = loader.render_to_string(
                "rhizom/graph_edit/add_rel.html",
                {"graph": graph, "newrel_form": newrel_form, "person": person},
                self.request)
            return JsonResponse(
                {"status": "error", "action": "replace", "content": content})
        source, _created = Person.objects.get_or_create(
            graph=graph, name=newrel_form.cleaned_data["source"])
        target, _created = Person.objects.get_or_create(
            graph=graph, name=newrel_form.cleaned_data["target"])
        if source.pk > target.pk:
            source, target = target, source  # source is always the lowest id
        if Relationship.objects.filter(
                source=source, target=target,
                reltype__pk=newrel_form.cleaned_data["rtype"]).exists():
            content = loader.render_to_string(
                "rhizom/graph_edit/add_rel.html",
                {"graph": graph, "newrel_form": newrel_form, "person": person},
                self.request)
            return JsonResponse(
                {"status": "error", "action": "replace", "content": content,
                 "message": _("This relationship already exists.")})
        newlink = Relationship.objects.create(
            source=source, target=target,
            reltype_id=newrel_form.cleaned_data["rtype"],
            dotted=newrel_form.cleaned_data["dotted"])
        graph.last_modification = now()
        graph.save()
        result = {"status": "OK", "message": _("Relationship added.")}
        if person:
            if source.pk == person.pk:
                newlink.other = newlink.target
            elif target.pk == person.pk:
                newlink.other = newlink.source
            content = loader.render_to_string(
                "rhizom/graph_edit/edit_rel.html",
                {"graph": graph, "rel": newlink}, self.request)
            result.update({"action": "add", "content": content})
        else:
            newrel_form = NewRelationship(graph=graph)  # Get a clean instance
            content = loader.render_to_string(
                "rhizom/graph_edit/new_rel.html",
                {"graph": graph, "newrel_form": newrel_form},
                self.request)
            result.update({"action": "replace", "content": content})
        return JsonResponse(result)


class GraphRelEdit(View):

    def _get_rel(self):
        self.graph = get_object_or_404(Graph, pk=int(self.kwargs["graph"]))
        if not self.graph.allowed_for(self.request.user, "edit"):
            raise PermissionDenied
        return get_object_or_404(Relationship, pk=int(self.kwargs["rel"]))

    def put(self, *args, **kwargs):
        rel = self._get_rel()
        put_data = QueryDict(self.request.body, encoding=self.request.encoding)
        form = RelationshipForm(put_data, instance=rel)
        if not form.is_valid():
            messages = []
            for fieldname, errors in form.errors.items():
                for error in errors:
                    messages.append("{}: {}".format(
                        form.fields[fieldname].label, error))
            return JsonResponse({
                "status": "error",
                "message": "<br/>".join(messages),
                })
        if not form.has_changed():
            return JsonResponse({
                "status": "OK",
                "message": _("No modification."),
                })
        form.save()
        self.graph.last_modification = now()
        self.graph.save()
        rel.other = Person.objects.get(pk=int(put_data["other"]))
        assert rel.other.pk in (rel.source.pk, rel.target.pk)
        content = loader.render_to_string(
            "rhizom/graph_edit/edit_rel.html",
            dict(graph=self.graph, rel=rel), self.request)
        return JsonResponse(dict(
                status="OK", action="replace", content=content,
                message=_("Relationship modified.")))

    def delete(self, *args, **kwargs):
        rel = self._get_rel()
        persons = (rel.source, rel.target)
        rel.delete()
        # Cleanup orphans
        for person in persons:
            if not Relationship.objects.filter(
                    Q(source=person) | Q(target=person)
                    ).exists():
                person.delete()
        self.graph.last_modification = now()
        self.graph.save()
        return JsonResponse(dict(
                status="OK", action="delete",
                message=_("Relationship removed.")))

rhizom/views/profile.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic.edit import UpdateView

from rhizom.forms import UserProfileForm


class ProfileView(LoginRequiredMixin, UpdateView):

    template_name = "rhizom/profile/profile.html"
    model = get_user_model()
    form_class = UserProfileForm
    success_url = reverse_lazy("rhizom:profile")

    def get_object(self):
        return self.request.user

    def get_initial(self):
        initial = super().get_initial()
        initial["locale"] = (
            self.object.rhizom_profile.locale or self.request.LANGUAGE_CODE)
        return initial

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        return kwargs

rhizom/templates/rhizom/graph_admin/edit_accesses.html
{% load i18n %}
{% load bootstrap_tags %}

<div class="form-table accesses">
    <div class="form-table-head">
        <div class="form-table-cell">{% trans "Username" %}</div>
        <div class="form-table-cell">{% trans "Access level" %}</div>
        <div class="form-table-cell"></div>
    </div>
    <form role="form" method="post" class="form-inline"
          action="{% url 'rhizom:graph_admin_access' graph=graph.pk %}">
        {% bootstrap_form_inline form with_label=False %}
        <div class="form-group">
            <button name="_method" value="POST" data-loading-text="..."
                    class="btn btn-sm btn-primary" title="{% trans "Add" %}">
                <span class="glyphicon glyphicon-plus"></span>
            </button>
        </div>
    </form>
    {# Public access #}
    {% if not has_public_access %}
    <form role="form" method="post" class="form-inline"
          action="{% url 'rhizom:graph_admin_access' graph=graph.pk %}">
        {% csrf_token %}
        <div class="form-group">
            <p class="form-control-static">{% trans "Public" %}</p>
        </div>
        <div class="form-group">
            <select name="level" class="form-control">
                <option value="" selected>{% trans "No access" %}</option>
                {% for level_id, level_name in perm_choices %}
                <option value="{{ level_id }}"
                    {% if level_id == perm.level %} selected {% endif %}
                    >{{ level_name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <button name="_method" value="POST" data-loading-text="..."
                    class="btn btn-sm btn-primary" title="{% trans "Add" %}">
                <span class="glyphicon glyphicon-plus"></span>
            </button>
        </div>
    </form>
    {% endif %}
    {# Private access #}
    {% for perm in graph.permission_set.all %}
    <form role="form" method="post" class="form-inline"
          action="{% url 'rhizom:graph_admin_access' graph=graph.pk pk=perm.pk %}">
        {% csrf_token %}
        <div class="form-group">
            <p class="form-control-static">
                {% if perm.user %}
                    <span {% if perm.user.display_name %}title="{{ perm.user.display_name }}"{% endif %}>
                        {{ perm.user.username }}
                    </span>
                {% else %}
                    {% trans "Public" %}
                {% endif %}
            </p>
        </div>
        <div class="form-group">
            <select name="level" class="form-control">
                {% for level_id, level_name in perm_choices %}
                <option value="{{ level_id }}"
                    {% if level_id == perm.level %} selected {% endif %}
                    >{{ level_name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <button name="_method" value="PUT" data-loading-text="..."
                    class="btn btn-sm btn-info" title="{% trans "Update" %}">
                <span class="glyphicon glyphicon-edit"></span>
            </button>
            <button name="_method" value="DELETE" data-loading-text="..."
                    class="btn btn-sm btn-warning" title="{% trans "Delete" %}">
                <span class="glyphicon glyphicon-remove"></span>
            </button>
        </div>
    </form>
    {% endfor %}
</div>


<script>
$(function() {
    setup_username_autocomplete(
        $('.accesses form input.autocomplete'),
        '{% url "rhizom:graph_admin_find_username" graph=graph.pk %}'
        );
});
</script>

rhizom/templates/rhizom/graph_admin/edit_reltypes.html
{% load i18n %}
{% load bootstrap_tags %}

<div class="form-table reltypes">
    <div class="form-table-head">
        <div class="form-table-cell">{% trans "Name" %}</div>
        <div class="form-table-cell">{% trans "Color" %}</div>
        <div class="form-table-cell">{% trans "Count" %}</div>
        <div class="form-table-cell"></div>
    </div>
    <form role="form" method="post" class="form-inline"
          action="{% url 'rhizom:graph_admin_reltypes' graph=graph.pk %}">
        {% bootstrap_form_inline form with_label=False %}
        <div class="form-group"></div>
        <div class="form-group">
            <button name="_method" value="POST" data-loading-text="..."
                    class="btn btn-sm btn-primary" title="{% trans "Add" %}">
                <span class="glyphicon glyphicon-plus"></span>
            </button>
        </div>
    </form>
    {% for reltype in graph.relationshiptype_set.all %}
    <form role="form" method="post" class="form-inline"
          action="{% url 'rhizom:graph_admin_reltypes' graph=graph.pk pk=reltype.pk %}">
        {% csrf_token %}
        <div class="form-group">
            <input type="text" name="name" class="form-control" value="{{ reltype.name }}" />
        </div>
        <div class="form-group">
            <input type="color" name="color" class="form-control" value="{{ reltype.color }}" />
        </div>
        <div class="form-group text-center">
            {{ reltype.rel_count }}
        </div>
        <div class="form-group">
            <button name="_method" value="PUT" data-loading-text="..."
                    class="btn btn-sm btn-info" title="{% trans "Update" %}">
                <span class="glyphicon glyphicon-edit"></span>
            </button>
            <button name="_method" value="DELETE" data-loading-text="..."
                    class="btn btn-sm btn-warning" title="{% trans "Delete" %}"
                    {% if reltype.rel_count != 0 %}
                    data-confirm="{% blocktrans with count=reltype.rel_count %}You are deleting {{ count }} relationships.{% endblocktrans %}"
                    {% endif %}
                    >
                <span class="glyphicon glyphicon-remove"></span>
            </button>
        </div>
    </form>
    {% endfor %}
</div>